Global:
  debug: false
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\rec_output
  save_epoch_step: 5
  eval_batch_step:
  - 0
  - 50
  cal_metric_during_train: true
  pretrained_model: C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\pretrained\en_PP-OCRv4_rec_train\best_accuracy
  checkpoints: null
  save_inference_dir: C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\rec_output\inference
  use_visualdl: false
  infer_img: null
  character_dict_path: C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\PaddleOCR\ppocr\utils\en_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: false
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
    - CTCHead:
        Neck:
          name: svtr
          dims: 120
          depth: 2
          hidden_dims: 120
          kernel_size:
          - 1
          - 3
          use_guide: true
        Head:
          fc_decay: 1.0e-05
    - NRTRHead:
        nrtr_dim: 384
        max_text_length: 25
Loss:
  name: MultiLoss
  loss_config_list:
  - CTCLoss: null
  - NRTRLoss: null
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\rec_dataset
    ext_op_transform_idx: 1
    label_file_list:
    - C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\rec_dataset\rec_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 25
    - RecAug: null
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 32
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\rec_dataset
    label_file_list:
    - C:\Pyg\Projects\meathub\Meat_A_Eye-aimodels\ai-server\OCR\rec_dataset\rec_val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
